name: CI Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black bandit pytest pytest-cov
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Check code formatting with black
        run: |
          black --check .
      - name: Security analysis with bandit
        run: |
          bandit -r .
