name: Create Release

on:
  push:
    tags:
      - "v*.*.*"
      - "refs/tags/v*.*.*"

jobs:
  release:
    if: github.repository == 'cvele/playnite_web_mqtt'
    runs-on: ubuntu-latest
    steps:
      - name: Set version env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: release-drafter/release-drafter@v5
        with:
          disable-autolabeler: true
          name: ${{ env.RELEASE_VERSION }}
          tag: ${{ env.RELEASE_VERSION }}
          version: ${{ env.RELEASE_VERSION }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
