name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Bump Version
        id: version
        run: |
          pip install bump2version
          bump2version patch --allow-dirty

      - name: Create Git Tag
        run: |
          git tag -a v$(bumpversion --dry-run --list | grep new_version | sed -r s,"^.*=",,"g") -m "Release"
          git push origin --tags

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v$(bumpversion --dry-run --list | grep new_version | sed -r s,"^.*=",,"g")
          name: 'Release v$(bumpversion --dry-run --list | grep new_version | sed -r s,"^.*=",,"g")'
          body: "Automatic release with version bump."
          draft: false
          prerelease: false
