name: Create Release

on:
  workflow_dispatch:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract tag from GITHUB_REF
        if: startsWith(github.ref, 'refs/tags/')
        id: extract_tag
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Generate release notes
        if: startsWith(github.ref, 'refs/tags/')
        id: generate_release_notes
        run: |
          NOTES=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h - %s")
          echo "::set-output name=notes::$NOTES"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ env.tag }}
          name: ${{ env.tag }}
          body: ${{ steps.generate_release_notes.outputs.notes }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
