name: Create Tag

on:
  workflow_dispatch:
    inputs:
      semver_input:
        description: "Enter a specific version (optional), or leave blank to bump the minor version from the latest tag"
        required: false
        default: ""

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git user identity
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV

      - name: Parse the latest tag and bump minor version if no input provided
        id: set_version
        run: |
          if [ "${{ github.event.inputs.semver_input }}" != "" ]; then
            NEW_VERSION=${{ github.event.inputs.semver_input }}
          else
            LATEST_TAG=${{ env.latest_tag }}
            VERSION_REGEX="^v([0-9]+)\.([0-9]+)\.([0-9]+)$"
            if [[ $LATEST_TAG =~ $VERSION_REGEX ]]; then
              MAJOR="${BASH_REMATCH[1]}"
              MINOR="${BASH_REMATCH[2]}"
              PATCH="${BASH_REMATCH[3]}"
              PATCH=$((PATCH + 1))
              NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
            else
              echo "Latest tag does not follow semantic versioning. Using fallback v0.0.0."
              NEW_VERSION="v0.0.0"
            fi
          fi
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Check if tag already exists
        run: |
          if git rev-parse "$NEW_VERSION" >/dev/null 2>&1; then
            echo "Tag $NEW_VERSION already exists. Exiting."
            exit 0
          fi

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Create and push the signed tag
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          git tag -s ${{ env.new_version }} -m "Release ${{ env.new_version }}"
          git push origin refs/tags/${{ env.new_version }}
