name: Create Tag

on:
  workflow_dispatch:
    inputs:
      semver_input:
        description: "Enter a specific version (optional), or leave blank to bump the minor version from the latest tag"
        required: false
        default: ""

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure we have access to all commits and tags

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          # Get the latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $LATEST_TAG"
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV

      - name: Parse the latest tag and bump minor version if no input provided
        id: set_version
        run: |
          # If semver_input is provided, use that. Otherwise, bump the minor version.
          if [ "${{ github.event.inputs.semver_input }}" != "" ]; then
            NEW_VERSION=${{ github.event.inputs.semver_input }}
          else
            # Extract major, minor, and patch from the latest tag (assuming vMAJOR.MINOR.PATCH format)
            LATEST_TAG=${{ env.latest_tag }}
            VERSION_REGEX="^v([0-9]+)\.([0-9]+)\.([0-9]+)$"
            if [[ $LATEST_TAG =~ $VERSION_REGEX ]]; then
              MAJOR="${BASH_REMATCH[1]}"
              MINOR="${BASH_REMATCH[2]}"
              PATCH="${BASH_REMATCH[3]}"
              # Bump the minor version
              MINOR=$((MINOR + 1))
              NEW_VERSION="v${MAJOR}.${MINOR}.0"
            else
              echo "Error: Latest tag $LATEST_TAG does not follow semantic versioning (vMAJOR.MINOR.PATCH)."
              exit 1
            fi
          fi
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create and push the new tag
        run: |
          # Create the new tag and push it to the repository
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}
