name: Validate with hassfest

on:
  pull_request:
  merge_group:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "home-assistant/actions/hassfest@master"
